### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [justanhduc/ray-casting#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114332274-7bc7bb00-9b78-11eb-9bf0-975179e7c4a2.png)

thank you  
best regards to you  
William

**Comment by justanhduc** [comment]
Hi @WilliamWangPeng. That file is my own data. For a demo, you can create a simple sphere. For e.g., 

```
float* getSphere(float radius, int dim, float range) {
    auto spacing = (float) range / (dim - 1);
    auto *sphere = new float[dim * dim * dim];
    auto x = 0, y = 0, z = 0;
    for (auto i = -range/2; i <= range/2; i+=spacing, z++, x=0, y=0)
        for (auto j = -range/2; j <= range/2; j+=spacing, y++, x=0)
            for (auto k = -range/2; k <= range/2; k+=spacing, x++) {
                auto v = pow(i, 2) + pow(j, 2) + pow(k, 2) - pow(radius, 2);
                auto idx = z*dim*dim + y * dim + x;
                sphere[idx] = v;
            }
    return sphere;
}
```
and in main

```
const int dim_x = 128, dim_y = 128, dim_z = 128;
auto *tsdf = getSphere(1., dim_x, 3.);
```

And remember to set `eye` outside of the sphere.
